api_key: ""
model: "deepseek-chat"
base_url: "https://api.deepseek.com"
concurrency: 5
include_exts:
  [
    ".go",
    ".py",
    ".java",
    ".php",
    ".js",
    ".ts",
    ".vue",
    ".jsx",
    ".tsx",
    ".html",
    ".css",
    ".scss",
    ".less",
    ".sass",
    ".styl",
    ".stylus",
    ".json",
  ]
